### PR TITLE
All status codes are logged and the status_code is added as a binary annotation

### PR DESCRIPTION
**Pull request by kaisen**

### CODE REVIEW

**Comment by mjbryant** [comment]
Looks good to me. @prat0318 was there an original reason we weren't logging spans for non-successful requests?

**Comment by prat0318** [comment]
It was mostly to reduce the traced call volumes to the successful ones as we should not care about traces of 4xx client error calls. Secondly, the non 2xx trace would not be complete and would not provide sufficient information (for scenarios where traces are picked from dashboard).

I can see usecase of it for on demand traces though. Is that the intent? It would be cool to quickly find out the origin of 5xx using zipkin.

**Comment by kaisen** [comment]
@prat0318 yeah, the main intent is to allow on-demand tracing for server errors. At least one person has asked for this feature and I figured it will add to the usefulness of zipkin.

**Comment by prat0318** [comment]
makes sense.

**Comment by mjbryant** [comment]
:shipit:

**Pull request merged**
