### PR TITLE
Add ability to override 'service_name' when logging client spans.

### PR DESCRIPTION
**Pull request by mjbryant**
Bumps to 0.8.0. Addresses Issue #20.

### CODE REVIEW

**Comment by mjbryant** [comment]
A bit messier than it could be, since I also changed every occurrence of "endpoint_attrs" to "thrift_endpoint", since I thought it more accurately captured what python object we were actually passing around.

**Comment by prat0318** [comment]
On second thoughts, `client: True` option can be replaced with the existance of `service_name` key. This is because, if there is a new client span, it SHOULD have a new name. That would be back incompat change though :-/

**Comment by prat0318** [comment]
:+1: looks good to me overall. We should update our tutorial_happyhour servicedocs with this.

**Comment by mjbryant** [comment]
Let's ship this as-is, then. We can make a backwards-incompatible change that removes the is_client key later. Sound good?

**Comment by prat0318** [comment]
yup, lets create a ticket and shipt it

On Tuesday, March 1, 2016, Michael Bryant <notifications@github.com> wrote:

> Let's ship this as-is, then. We can make a backwards-incompatible change
> that removes the is_client key later. Sound good?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Yelp/pyramid_zipkin/pull/21#issuecomment-191028091>.
>


-- 
Prateek Agarwal

**Pull request merged**
