### PR TITLE
Make span name from GET to GET /foo

### LINKED ISSUE #27: Add span name as : get: <http.uri> instead of just get

### PR DESCRIPTION
**Pull request by prat0318**
Fixes #27

### CODE REVIEW

**Comment by gkayling** [comment]
lgtm!

**Comment by mjbryant** [comment]
LGTM! Could you bump version to 0.8.2 as well? I don't think this counts as a backwards-incompatible change.

**Comment by mjbryant** [comment]
@prat0318 I'm going to merge master, which now includes https://github.com/Yelp/pyramid_zipkin/pull/29. I'm then going to release the [ClientSpanContext PR](https://github.com/Yelp/pyramid_zipkin/pull/29), the [hex IDs PR](https://github.com/Yelp/pyramid_zipkin/pull/26), and this PR as `v0.9.0`, as per discussions with @kaisen on Friday.

**Comment by mjbryant** [comment]
Closing this, since I just reapplied the exact same change https://github.com/Yelp/pyramid_zipkin/pull/30 on top of a new master.

**Pull request closed without merging**
