### PR TITLE
default service_name to 'unknown'

### PR DESCRIPTION
**Pull request by bplotnick**
service_name is required, but there is no reason why we should die if it isn't set

### CODE REVIEW

**Comment by kaisen** [comment]
let's update the changelog and bump this to 0.12.2

**Comment by kaisen** [comment]
:shipit:

**Comment by adriancole** [comment]
late to the party, but there's some subtlety here:

if you are a client, you don't often don't know what the service name is.
In this case, use empty string to defer to the server-side of the span.

If you are a server, and you also don't know what your service name is,
then use "unknown" so that the span is queryable.

https://github.com/openzipkin/zipkin-api/blob/master/thrift/zipkinCore.thrift#L262

**Comment by bplotnick** [comment]
Thanks for the note @adriancole!

I looked at that version of zipkinCore.thrift for this, and I think we are in the latter category of acting as the server. Prior to this, we would just throw and exception and die if the pyramid app did not set `service_name` in the pyramid registry. (Our [docs](docs/source/configuring_zipkin.rst) state that service name is required, but we do no validation). This change is to be more forgiving when applications do not set this. And having the span be queryable is a nice bonus 😄

I totally might be missing something, so let me know if I am not making sense.

**Comment by adriancole** [comment]
Sounds like you understand what I was trying to say. looks good then!

**Pull request merged**
